package entitys;
// default package
// Generated Aug 9, 2019 8:28:56 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtHoadonId generated by hbm2java
 */
@Embeddable
public class CtHoadonId implements java.io.Serializable {

	private String idhoadon;
	private String idlinhkien;

	public CtHoadonId() {
	}

	public CtHoadonId(String idhoadon, String idlinhkien) {
		this.idhoadon = idhoadon;
		this.idlinhkien = idlinhkien;
	}

	@Column(name = "IDHOADON", nullable = false)
	public String getIdhoadon() {
		return this.idhoadon;
	}

	public void setIdhoadon(String idhoadon) {
		this.idhoadon = idhoadon;
	}

	@Column(name = "IDLINHKIEN", nullable = false)
	public String getIdlinhkien() {
		return this.idlinhkien;
	}

	public void setIdlinhkien(String idlinhkien) {
		this.idlinhkien = idlinhkien;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtHoadonId))
			return false;
		CtHoadonId castOther = (CtHoadonId) other;

		return ((this.getIdhoadon() == castOther.getIdhoadon()) || (this.getIdhoadon() != null
				&& castOther.getIdhoadon() != null && this.getIdhoadon().equals(castOther.getIdhoadon())))
				&& ((this.getIdlinhkien() == castOther.getIdlinhkien())
						|| (this.getIdlinhkien() != null && castOther.getIdlinhkien() != null
								&& this.getIdlinhkien().equals(castOther.getIdlinhkien())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdhoadon() == null ? 0 : this.getIdhoadon().hashCode());
		result = 37 * result + (getIdlinhkien() == null ? 0 : this.getIdlinhkien().hashCode());
		return result;
	}

}
