package entitys;
// default package
// Generated Aug 9, 2019 8:28:56 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Danhmuclinhkien generated by hbm2java
 */
@Entity
@Table(name = "DANHMUCLINHKIEN", schema = "dbo", catalog = "DOANPTUD")
public class Danhmuclinhkien implements java.io.Serializable {

	private String id;
	private String ten;
	private Set<Linhkien> linhkiens = new HashSet<Linhkien>(0);

	public Danhmuclinhkien() {
	}

	public Danhmuclinhkien(String id, String ten) {
		this.id = id;
		this.ten = ten;
	}

	public Danhmuclinhkien(String id, String ten, Set<Linhkien> linhkiens) {
		this.id = id;
		this.ten = ten;
		this.linhkiens = linhkiens;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TEN", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danhmuclinhkien")
	public Set<Linhkien> getLinhkiens() {
		return this.linhkiens;
	}

	public void setLinhkiens(Set<Linhkien> linhkiens) {
		this.linhkiens = linhkiens;
	}

}
