package entitys;
// default package
// Generated Aug 9, 2019 8:28:56 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donhang generated by hbm2java
 */
@Entity
@Table(name = "DONHANG", schema = "dbo", catalog = "DOANPTUD")
public class Donhang implements java.io.Serializable {

	private String id;
	private Khachhang khachhang;
	private Nhanvien nhanvien;
	private byte[] ngaydat;
	private Date ngaygiao;
	private Date ngaychuyen;
	private String diachinhanhang;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Donhang() {
	}

	public Donhang(String id) {
		this.id = id;
	}

	public Donhang(String id, Khachhang khachhang, Nhanvien nhanvien, byte[] ngaydat, Date ngaygiao, Date ngaychuyen,
			String diachinhanhang, Set<Hoadon> hoadons) {
		this.id = id;
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.ngaydat = ngaydat;
		this.ngaygiao = ngaygiao;
		this.ngaychuyen = ngaychuyen;
		this.diachinhanhang = diachinhanhang;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDKHACHHANG")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNHANVIEN")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Column(name = "NGAYDAT")
	public byte[] getNgaydat() {
		return this.ngaydat;
	}

	public void setNgaydat(byte[] ngaydat) {
		this.ngaydat = ngaydat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYGIAO", length = 10)
	public Date getNgaygiao() {
		return this.ngaygiao;
	}

	public void setNgaygiao(Date ngaygiao) {
		this.ngaygiao = ngaygiao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYCHUYEN", length = 10)
	public Date getNgaychuyen() {
		return this.ngaychuyen;
	}

	public void setNgaychuyen(Date ngaychuyen) {
		this.ngaychuyen = ngaychuyen;
	}

	@Column(name = "DIACHINHANHANG")
	public String getDiachinhanhang() {
		return this.diachinhanhang;
	}

	public void setDiachinhanhang(String diachinhanhang) {
		this.diachinhanhang = diachinhanhang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donhang")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
