package entitys;
// default package
// Generated Aug 9, 2019 8:28:56 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Linhkien generated by hbm2java
 */
@Entity
@Table(name = "LINHKIEN", schema = "dbo", catalog = "DOANPTUD")
public class Linhkien implements java.io.Serializable {

	private String id;
	private Danhmuclinhkien danhmuclinhkien;
	private Nhacungcap nhacungcap;
	private String ten;
	private int soluong;
	private BigDecimal dongiagoc;
	private BigDecimal dongiatrenhoadon;
	private String mota;
	private Set<CtHoadon> ctHoadons = new HashSet<CtHoadon>(0);

	public Linhkien() {
	}

	public Linhkien(String id, String ten, int soluong) {
		this.id = id;
		this.ten = ten;
		this.soluong = soluong;
	}

	public Linhkien(String id, Danhmuclinhkien danhmuclinhkien, Nhacungcap nhacungcap, String ten, int soluong,
			BigDecimal dongiagoc, BigDecimal dongiatrenhoadon, String mota, Set<CtHoadon> ctHoadons) {
		this.id = id;
		this.danhmuclinhkien = danhmuclinhkien;
		this.nhacungcap = nhacungcap;
		this.ten = ten;
		this.soluong = soluong;
		this.dongiagoc = dongiagoc;
		this.dongiatrenhoadon = dongiatrenhoadon;
		this.mota = mota;
		this.ctHoadons = ctHoadons;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDANHMUC")
	public Danhmuclinhkien getDanhmuclinhkien() {
		return this.danhmuclinhkien;
	}

	public void setDanhmuclinhkien(Danhmuclinhkien danhmuclinhkien) {
		this.danhmuclinhkien = danhmuclinhkien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNHACUNGCAP")
	public Nhacungcap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(Nhacungcap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

	@Column(name = "TEN", nullable = false)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "SOLUONG", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Column(name = "DONGIAGOC", scale = 4)
	public BigDecimal getDongiagoc() {
		return this.dongiagoc;
	}

	public void setDongiagoc(BigDecimal dongiagoc) {
		this.dongiagoc = dongiagoc;
	}

	@Column(name = "DONGIATRENHOADON", scale = 4)
	public BigDecimal getDongiatrenhoadon() {
		return this.dongiatrenhoadon;
	}

	public void setDongiatrenhoadon(BigDecimal dongiatrenhoadon) {
		this.dongiatrenhoadon = dongiatrenhoadon;
	}

	@Column(name = "MOTA")
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "linhkien")
	public Set<CtHoadon> getCtHoadons() {
		return this.ctHoadons;
	}

	public void setCtHoadons(Set<CtHoadon> ctHoadons) {
		this.ctHoadons = ctHoadons;
	}

}
